apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: hursittopal/test-nginx:1.0.1
        imagePullPolicy: IfNotPresent

      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config