version: "3.1"
services:
    test-nginx:
        build: nginx
        restart: on-failure
        ports:
          - "8881:80"
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - "test-fpm"
          - "test-mysql"
          - "test-mongo"
          - "test-memcached"
          - "test-rabbitmq"

    test-fpm:
        container_name: test-fpm
        build:
          context: ./../
          dockerfile: ./docker/php-fpm/Dockerfile
        working_dir: /application
        restart: on-failure
        volumes:
          - ./../app:/application:cached
          - ~/.ssh/:/root/.ssh/

    test-mysql:
      build:
        context: ./mysql
      restart: on-failure
      environment:
        - MYSQL_USER=${DATABASE_USER}
        - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      volumes:
        - ./mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql

    test-mongo:
      build:
        context: ./mongo
      restart: on-failure

    test-memcached:
      build:
        context: ./memcached
      restart: on-failure

    test-rabbitmq:
      build:
        context: ./rabbitmq
      restart: on-failure
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}