apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpm-deployment
  labels:
    app: fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fpm
  template:
    metadata:
      labels:
        app: fpm
    spec:
      containers:
        - name: fpm
          image: hursittopal/test-fpm:1.0.7
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          volumeMounts:
            - name: app-env-config-volume
              mountPath: /application/.env
              subPath: app-parameters

            - name: ssh-secret-volume
              mountPath: /root/.ssh/id_rsa
              subPath: ssh-privatekey

            - name: ssh-secret-volume
              mountPath: /root/.ssh/id_rsa.pub
              subPath: ssh-publickey

      volumes:
        - name: app-env-config-volume
          configMap:
            name: app-env-config
        - name: ssh-secret-volume
          secret:
            secretName: ssh-secret
            defaultMode: 0600
